---
default:
  environments:
    - "production"
    - "development"
  config:
    logging:
      level: 40
    retrieval:
      max_age_in_minutes: 15
      url_template: "https://api.energyzero.nl/v1/energyprices?fromDate={{ start_date }}T{{ start_time }}.000Z&tillDate={{ end_date }}T{{ end_time }}.999Z&interval=4&usageType={{ type }}&inclBtw=true"
    data_folder: ${env:DATA_FOLDER}
    timezone: Europe/Amsterdam
    homeassistant:
      url: ${env:HA_URL}
      token: ${env:HA_TOKEN}

development:
  logging:
    level: 10
  retrieval:
    max_age_in_minutes: 15
